name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [function1, function2, function3, function4, function5, function6]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install shared dependencies
      run: |
        cd shared
        npm install

    - name: Build and deploy ${{ matrix.function }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        cd functions/${{ matrix.function }}
        npm install
        npm run build # Assumes a build script is defined in your package.json
        aws lambda update-function-code --function-name ${{ matrix.function }} --zip-file fileb://function.zip