name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - AddProductLambda
          - DeleteProductLambda
          - GetUserProductsLambda
          - UpdateProductPriceLambda
          - UserLoginLambda
          - UserRegistrationLambda
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install shared dependencies
      run: |
        npm install --prefix shared

    - name: Prepare and deploy each function
      run: |
        FUNCTION_DIR=functions/${{ matrix.function }}
        DEPLOYMENT_DIR=deployment/${{ matrix.function }}
        
        # Create deployment directory
        mkdir -p $DEPLOYMENT_DIR
        
        # Copy function-specific file
        cp $FUNCTION_DIR/index.mjs $DEPLOYMENT_DIR/
        
        # Copy node_modules
        cp -r shared/node_modules $DEPLOYMENT_DIR/
        
        # Zip the deployment package
        cd $DEPLOYMENT_DIR
        zip -r ../../$FUNCTION_DIR/function.zip .
        
        # Deploy to AWS Lambda (ensure AWS CLI v2 is used)
        aws lambda update-function-code --function-name ${{ matrix.function }} --zip-file fileb://$FUNCTION_DIR/function.zip
        
        # Cleanup
        cd ../../
        rm -rf $DEPLOYMENT_DIR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
